server.port= 9090
spring.datasource.url=jdbc:mysql://localhost:3306/studentManagement
spring.datasource.username=root
spring.datasource.password=pvpsit

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp